---

name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.13.x'
          - '1.12.x'
          - '1.11.x'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1.1.2
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        run: go test -v ./...
